### ISSUE TITLE
StopMotion capture on another level for erasing rigs.

### ISSUE THREAD

**Issue by caricaturize** [turtletooth/tahoma2d#170]
When doing stop motion we often need to take a clean background plate so that we can 'post-process' erase the rig and then the background would show through.

Would you be able to make it so you can capture onto another level (I suppose any level that you have selected in the timeline) ?

I don't know how this feature is done in dragonframe or if the 'separate level' is involved at all.

(Keep in mind that when we erase the top capture it has to show thru transparent so the bottom level shows thru) I'm not sure if that is handled natively right now.  (Right now the captured level is 'locked' and I can't use the eraser so that would have to be functional')

Thank you so much.

**Comment by artisteacher** [comment]
I'd probably try using a matte fx instead of erasing, but you can already do stop motion capture on multiple levels:

1. Make a new level name for the 2nd level
<img width="322" alt="Screen Shot 2020-09-14 at 5 19 04 PM" src="https://user-images.githubusercontent.com/21159116/93139641-204f5080-f6af-11ea-96b0-ee63322a217d.png">
2. In the Timeline/Xsheet, select an empty cell or the first cell in the level you want beneath the new level


3. Click on "current frame"
<img width="304" alt="Screen Shot 2020-09-14 at 5 25 39 PM" src="https://user-images.githubusercontent.com/21159116/93139772-5ab8ed80-f6af-11ea-8789-dddb21c0569b.png">
4. Lower the opacity as needed
<img width="338" alt="Screen Shot 2020-09-14 at 5 28 16 PM" src="https://user-images.githubusercontent.com/21159116/93140010-ba16fd80-f6af-11ea-97a9-c28285e606ac.png">
5. Start capturing

**Comment by artisteacher** [comment]
Perhaps the read only should be a checkable option. I like to have the captured images read-only myself. It prevents my students from unintentionally making destructive changes to their photos.

As a workaround for now, you should be able to merge the captured level with an empty raster level with the same number of frames. Then you'll have an editable version to erase on.

**Comment by caricaturize** [comment]
Wow, yes I tried to capture on another level and indeed I can per your instructions. Thank you

I will look into the merge capture so I can erase the top (rig) layer. I assume when I erase it will show transparent and not white?I'll let you know.
Otherwise I will experiment with the matte fx. I'd have to experiment.

Tahoma is incredible that it can post-edit out rigs. Even dragonframe doesn't have a way to do this and recommends AE or photoshop!
Thank you

**Comment by RodneyBaker** [comment]
Recommend closing.
