### ISSUE TITLE
Ability to name levels in level strip

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#232]
Any chance we could have a Rename feature in the Levels Strip?

I noticed you can name them in the XSheet/Timeline, so at least there's a very easy workaround.  So, it's certainly not a critical feature request.  Just figured it might be nice to be able to do it in the Levels Strip, too.

**Comment by artisteacher** [comment]
Since you mentioned the Timeline/Xsheet, you might be thinking of the column/layer names rather than the level names. Layer/column names can be edited directly in the Timeline/Xsheet. Layers/columns aren't quite the same as a level, so they shouldn't be renamed in the Level Strip.

Renaming levels might not behave as you expect. Levels have a "display name" and then the name of the actual level file(s). Those are the same, unless you rename a level in the level settings. That actually changes the display name. Changing the name of the files themselves can be problematic since levels are often reused between multiple scenes. Changing the name would break those paths. 

It could be nice to be able to change truly change the level name & have the path in the current scene updated automatically. There'd have to be a warning dialog that the action might break the paths in other scenes.

Back on topic, an option to rename the display name for the active level could be helpful in the Level Strip. Maybe a context menu option?

**Comment by ladlon** [comment]
Hello again!  I was actually meaning the letter names of the groups of drawings, not the columns.  Ya, the columns are easily renamed... but the drawing groups (not the numbers, but the (at least initially) letter names.

Then again, I'm coming from a non-traditional animation background.  The use of xsheets and traditional methods is 'familiar' to me (only in that I knew OF it)... but not something I ever used myself... until now.  So, I may not be following proper protocol.

I certainly rename the columns... and generally, it would seem that the groups of drawings I would do would all be related (ex. all the mouths, or all the eyes, etc).... so, I figured I'd rename those groups (the 'levels', right?), so that the pulldown list of levels would be a bit more intuitive than just a list of letters with no reference to what they contain.

But, ya, it seemed like trying to rename those caused all kinds of bad things... aside from doing it via the Scene Cast.  Doing it in the timeline would cause the first (selected) frame to become a new frame, and all the following (hold) frames after that would retain the original drawing, but be separate from that first frame.  Kinda broke things when I tried, so I quickly stopped doing that!  Meanwhile, in the Level Strip, I was puzzled by why you couldn't click on the level title and rename it... nor even do it via a right click menu....   and eventually, I got the impression I was trying to do something that I really shouldn't do.

But, really, the only reason I was trying to rename them, rather than leaving their automatically assigned names, was to make the levels list something recognizable (Eyes, Mouth, etc... rather than A, B, C, etc).  I just saw myself blindly selecting the level names until I found the one I was after... and feared, too, that the little level thumbnails might be hard to distinguish from one another when it came to drawings that had subtle differences in them.  Just trying to avoid a lot of blind select clicking until I found the right things...

On the other hand... A single letter IS more appropriate, in the sense that there's not much text space in the cell as it is, so you'd surely just get brutally truncated versions of your names...  Mouth would probably just be Mo... or something like that.

But, ya, if you haven't seen it, check out the Scene Cast.  That's a nice 'all on one page' way to review and edit the level names.  Doesn't seem to cause chaos, either.... I don't think.

**Comment by artisteacher** [comment]
If you aren't already, try using a new level dialog when you create a level - that way you can name the levels from the start & aren't stuck with the alphabetical naming system. If you add a command bar, the first 3 buttons open the new level dialog for each level type. There's also a new level button on the top left of the Timeline/Xsheet which defaults to default level type.

**Comment by RodneyBaker** [comment]
One way to see the full name of a level in the timeline/xsheet is to hover over it at which time the tooltip will appear displaying the full name.
