### ISSUE TITLE
Bugs to fix for 1.1

### ISSUE THREAD

**Issue by jeremybullock** [turtletooth/tahoma2d#256]
Hey everyone!

1.1 is right around the corner.  The last few weeks before the release are going to be dedicated to bug fixes (and build error fixes).

What bugs in Tahoma or OT do you see as a high priority and impacting the most users.

Big things like render crashes probably won't be tackled this round unless there are repeatable steps to get a crash.

I think aiming for a release in mid to late October is reasonable.

**Comment by RattusaurusRex** [comment]
The Undo bug is a pretty ugly one that I think most people have experienced.  I thought I had posted the following video to one of the bug reports for Undo, but it seems like I haven't.  At the start of the video, I'm also acting confused because 'Enable Creation in Hold Cells' somehow got turned on out of nowhere (I keep this setting off).  I don't know if this bug is still in Tahoma because I don't know how to make it happen.

[undo.zip](https://github.com/turtletooth/tahoma/files/5302719/undo.zip)

**Comment by artisteacher** [comment]
Personally for this round, I'd focus on UI issues that impact usability, reproducible crashes & any bugs introduced in Tahoma.

**Comment by jeremybullock** [comment]
@manongjohn Do you have any hopes or thoughts on what should be done before 1.1?

**Comment by jeremybullock** [comment]
@artisteacher I think I have taken care of most of the UI issues in the OpenToonz issues.  Are there any big things you are still seeing?  I've also taken care of a handful of crashes and bugs.  Still plenty to do though.

**Comment by artisteacher** [comment]
There's an issue with the cursor not updating properly - several possibly related issues are posted on OT. I thought it was just  hover not being recognized with a tablet, but sometimes the mouse cursor doesn't update properly too - even when there's no tablet. When it happens, it makes resizing panels much fussier for students new to Tahoma since the cursor doesn't change. I'm not sure what triggers the initial problem. Once it happens in a session, it seems to keep happening. Since it's currently unpredictable, I know it is unlikely to be fixed quickly.

**Comment by artisteacher** [comment]
Actually, that could just be #318 which is hopefully fixed already. Hovering is an issue with tablets though.

I'm wondering if guides should be visible in the 3D view?
<img width="1377" alt="Screen Shot 2020-10-07 at 9 29 07 PM" src="https://user-images.githubusercontent.com/21159116/95404939-64b3c200-08e4-11eb-8494-6c1132baef7a.png">
Beyond the guides looking glitchy, it's always super zoomed out when first switching to the 3d view. Reset view is more reasonable.

**Comment by jeremybullock** [comment]
I'm going to close this and let new bugs get their own issue.
