### ISSUE TITLE
Window extended (extremely) vertical, and 'disappears' when top edge clicked (....wee!)

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#315]
This may be a Windows thing... or a combo of Tahoma2D and windows... or something else.  Not sure.

It seemed to all start when I had the Schematic view maximized.  When I hit the Maximize shortcut key again (to restore all the other windows/palettes), I instead got what appeared to be a maximized timeline window.

But, after a while, it seemed like it was actually not 'maximized', but stretched large, as to pretty much squash the other windows out of view.

It was then that I also noticed that the full Tahoma2D window had the bottom edge extending WAY below the bottom of the monitor.  I only realized this, as the taskbar preview thumbnail of it showed a VERY vertical window.

Maximizing the Tahoma2D window (...by that, I mean Windows window maximizing, not solo'ing one of the Tahoma2D palettes), resulted in what SEEMED like a proper layout... but clicking the Restore Down window icon resulted in a window that obviously extended well past the bottom of the monitor edge.

So, I grabbed the title bar, moved the entire window down so I could grab the top edge, with the intention of then dragging it to scale down the vertical size of the window (since I couldn't grab the bottom edge, which was offscreen).

Doing that (click holding the top edge, so the Vertical Scaling Arrow mouse pointer appears) resulted in the entire Tahoma2D window 'disappearing' (...maybe teleporting further down, completely off the monitor screen.. as the taskbar 'bar/icon' was still present, indicating the program was still open).

This happened every time I attempted to drag (vertically scale) the top edge of the window.  Dragging the sides worked fine (horizontal scaling)... but even trying a corner scale (diagonal scale) caused the same 'disappearance'.

All I could do each time, was close Tahoma2D (via the taskbar icon) and relaunch it.  I could never fix the 'bottom extending off the screen' layout of the 'Restore Down' mode of the Tahoma2D window.  Luckily, the Maximized version works.

I suspect this might be at least partially connected to the issue where the (Windows) maximized version of the Tahoma2D window would not fully extend to fit the monitor, due (if I understand right) to Tahoma2D saving the position during each session, or something to that affect (...which apparently was already fixed and implemented into the upcoming Tahoma2D release).

It seemed like, at one point, the mouse pointer was strobing a bit, too...  So, I just did a full PC restart, as I figured something was bad, and I better just reset.

Sorry I can't really provide much more than that currently.  Just wanted to let you know, in case that triggers some theories or something.

Win7Pro

**Comment by artisteacher** [comment]
The stacking order of the windows can behave unexpectedly in OT (and hence Tahoma). Sometimes the most recently opened dialog or window displays underneath other windows (ie. Output Settings always displays in front of the render window https://github.com/opentoonz/opentoonz/issues/1846). In those cases, clicking on them to change the focus doesn't bring the window forwards - which would be expected & how other windows do work. In other cases, clicking outside of a window moves them behind the program window - because the program window is now in focus. This could be part of what you are experiencing. 

Instead of clicking on the top edge, you might be clicking just past the edge onto the program window - or at least that's what Tahoma thinks. I've definitely done that before. If that's what is happening, you should be able to find the missing window if you minimize Tahoma.

Sometimes the edge of a window or the dragbars in the Timeline can be hard to target. I'm not sure if it's user error, or Tahoma thinking the target area is just slightly lower/higher than it appears to be.

**Comment by jeremybullock** [comment]
I think this is fixed.  Please let me know if you continue to see problems.
