### ISSUE TITLE
Tutorials opentoonz and tahoma 

### ISSUE THREAD

**Issue by trixturbo** [turtletooth/tahoma2d#328]
I just started animating and I wondered if I can watch the Opentoonz tutorials when learning Tahoma. I am scared that I will confuse the two.

**Comment by RodneyBaker** [comment]
Now is an excellent time to watch Opentoonz tutorials and apply what is learned to what we see in Tahoma... because changes haven't gotten too different.  Waiting and watching them later might be a little more problematic BUT... that would be true of watching old and current Opentoonz tutorials when using future Opentoonz releases.  This will always be a little different.

Here's the deal... if you get confused... ask questions until you get the answers you need.
One good place to ask is via the Tahoma2D discord:  

https://discord.gg/kkNhD9N

Folks that hang out in the Tahoma2D discord tend to hang out in the Opentoonz discord as well.  :)

**Comment by artisteacher** [comment]
In the latest Alpha release for 1.1, there are some terminology changes:

Windows/panes now = Panels
Xsheet menu/Xsheet node in the schematic now = Scene
Sub-xsheet now = Sub-scene
Command bar/Xsheet toolbar now = Quick toolbar
Toonz raster levels now = Smart raster level

**Comment by jeremybullock** [comment]
This question would be better to be asked on the new Google group or in the Tahoma2D discord.
https://groups.google.com/g/tahoma2d
https://discord.gg/4HUXF6F

In the interest of clearing up the issue list here on GitHub, I'll be recommending this on a number of questions in the issues.
