### ISSUE TITLE
Expressions don't adjust when new columns added/moved... yet still work?

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#355]
I'm confused about something... and maybe it's a bug.

I use expressions that reference other columns a lot.  For example, I'll animate one column manually, and then have another column reference (say) the X position attribute of the first one (and maybe apply some modifier, like multiplying it by 1.5.

That all works fine.  But here's what I noticed...

The expression system seems to use the program-assigned names, rather than the custom names that you can assign, to make them more meaningful/recognizable.

So, let's say I create 5 columns (objects in my scene), and my 'master' column (the one I manually animate, and will be referenced) is Col4... and the 'coded' column (the one with the expression referencing the master) is Col1.  So, the expression on Col1's X attribute might be Col4.x * 1.5

All good so far, and it works.

Now let's add a new column (which gets named Col6 by the software, as there was previously 5).  Still good...

But, if we move Col6 (the new one) to a stack position where it is now between columns 3 and 4... the columns above it get renumbered, and our 'coded' column (previously named Col4) is now named Col5.

So, now you might wonder... what happens with the expression we created in Col1, which was referencing 'Col4'.  One would assume it keeps track of column order shifts, and somehow keeps locked to the 'proper' column it was originally assigned, regardless of where you might move it, or what you might name it.

Looking at the expression again on Col1, we see that it is actually still (at least visually, in the code) referencing Col4... the original, but now incorrect name of the column.  In theory, it should now be referencing the column that used to be Col3(?)... and therefore, our 'coded' column (Col1) SHOULD no longer be moving when our 'master' column (previously called Col4, now named Col5) moves.

What is odd, though, is that it appears it DOES still work, as if it is still referencing the proper column (...which, certainly, is a good thing... and makes me think it IS 'hardcoded' under the hood somehow, regardless of name and/or position).

So, aside from it being 'weird' that it works... it works... and that's good.

Except... it becomes very confusing, looking over the expressions... as they are now (visually) incorrect.  They are claiming to reference columns that they actually are not (...it's referencing Col5, yet it SAYS Col4).  Obviously, this can get really messy when you are trying to figure things out.

So, I'm not sure what the deal is with that.  If this is not intentional, then I would definitely suggest that any expressions referencing a column should get updated (change the name used in the expression) any time the target's name gets changed due to being moved in the column stack and/or shifted as the result of a column being inserted 'below' (column stacking order) it.

On a related note, it's odd that the Function Editor displays the 'software-given' names, rather than the custom (user-assigned) names (if given).  I mentioned that in a previous Feature Suggestion, where I found the display of BOTH the Col name AND the user name cluttered/distracting (since you will ALWAYS be looking for the USER name, as the whole reason you named it is to know what it is (ex. Head, Arm, Tree) as opposed to a non-descriptive 'Col5, Col12, etc'.

That said, I find it a bit odd that the expressions don't utilize the user name, rather than the Col name... since (beyond the issue outlined above), expressions would be far more logical/visually easier to identify/understand if they used the user names (ex. Car.x, rather than Col12).

So, the expressions don't appear to get BROKEN by the target getting auto-renamed due to getting moved, or shifted due to a column being added before it... but the name isn't updated, resulting in a confusing 'incorrect' display (and making it impossible to ultimately debug any issues with expressions).

I'm curious to hear some feedback on this...

Cheers

**Comment by RodneyBaker** [comment]
Hi @ladlon  
You may be interested in this PR which has not yet been merged into Opentoonz:

https://github.com/opentoonz/opentoonz/pull/3375

**Comment by ladlon** [comment]
Hi, Rodney.  That looks neat, actually.

The weird thing is, despite the text/name in the expression not getting updated when the target is moved (in the column stack), it doesn't appear to break.  It's like it's only a display issue, but the internal formula (expression) is still referencing the proper (moved) column.  But, ya, it does create a very confusing display... and over the course of serveral column position shifts, many/all of your expressions will be (display-wise) wrong.

What I don't get, is why the expressions don't use the user-name for the column (ex. Nose), rather than the procedural one (ex. Col23).  Not only would that make for easier expression regognition/readability... but also the name would not be affected by any relocation of the column in the column stack order.  It would have TWO benefits (...Three, actually, since displaying just the user-name in the function editor, too, would make for a much cleaner/more readable function editor list (left side).

All columns should START with a procedural name (ex. Col12), but then you can rename THAT name to something custom (ex. Car)... and so you'd have only one 'name' (and that would be the one used in expressions, too).

**Comment by RodneyBaker** [comment]
Yes, it will be when the use of the column/object's custom tile eventually can be used as well.
A core reason to need the new expression reference manager is to pave the way for such changes to any custom reference/title the use may supply.   Currently if anything changes the link will break.

Moving things around in the column stack does not change it's underlying name and so the link in the expression remains solid.
There are some exceptions to this.

The reason expressions don't use the custom title is that the custom title/reference is because without the code to allow for it expressions would easily break.  Users cloning the Nose column.. renaming it to Nose_clone1... and then using that clone instead of the original... which they've then deleted... might wonder why their expression no longer works.

So... the expressions feature is moving in that direction... and it will be nice when we have the ability to customize expressions to the nth degree.  :)

**Comment by ladlon** [comment]
Interesting point about the clone, yet isn't the 'clone' just a standalone duplicate with no connections to the original source?  Or, is it like an instance, where it is a live duplicate, referencing the original?

(BTW, forgive me if my thoughts here are painfully naive or I'm missing some key concept that puts my whole thinking in the trash.  I'm just seeing if there's not some previously unconsidered solution/concept or something... plus, also educating myself through insightful discussion wtih you guys...)

If it's just a standalone duplicate (similar to a cut and paste version), then is it not a completely unique item, with no connections?  even the name is unique (Nose_clone1, I would imagine, is just as 'similiar' to the software to Nose as FireHydrant is to nose, since I am assuming it's viewing the name, and if it's not exactly the same, then it's not equal, regardless of how 'close' it is as far as the name is concerned?  Would it not just treat it as a completely unique/separate item, with no assumption/knowledge of any connection?  And, if the original is deleted, would it not be unaffected, just as it's not affected if you delete (say) 'Eye'.

And, if it's an instance (live clone), would deleting the original not wipe out both items, since the live clone is feeding from the original, and if the original no longer exists, the clone wouldn't exist either, because it is referencing nothing?

And, again, what I feel may be an important consideration, is that these issues that might occur when these suggestions are applied to an expression referencing a column seemingly will not be happening too often, as I assume that (of all the columns in a scene) only a small number of them may actually use expressions, if any... and in cases where there is an unsolvable conflict (ex. use of custom characters in a name conflicting with expression code), you could simply pop up a warning, saying 'The selected column needs to be renamed to something without special characters'... which is an easy fix by the user, and means that you don't have to disallow special character for all other (majority?) columns... just the few instances where there is a conflict.

If I'm way off on this, just ignore it.

**Comment by RodneyBaker** [comment]
A clone in Opentoonz is an independent, unlinked duplicate of the original.
With the exception of the file name, which the user is prompted to change at time of creation it is an exact duplicate of the original at the time of creation but changes made to either the original or the clone thereafter will not impact the other... as they are separate and unlinked.  

Compare this with a standard copy of an exposure in the xsheet/timeline which is simply a reference to the original.
In that case the changing one will automatically update the other(s).

There is no such thing that I am aware of as a 'live clone'.  That would just be a link, reference or exposure to the original.
This is a common construct in other applications however and can cause some confusion when working in Opentoonz.
Cloning is a term used in Opentoonz for the process of creating a copy that will then be unique in and of itself and independent from the original.   (Think of it as if you were the clone of the real ladlon which at times would be beneficial but ultimately you want to be your own person so you strike out on your own and do your own thing)

Returning to the idea of expressions...
An expression isn't linked... although the new Expression Reference Manager attempts to do some linking/updating to keep up with a users changes.  

The expression just points to/references objects (in most cases a column),
So currently, an expression in the rotation channel of column 2 that states "col1.rot" will cause column 2 to rotate the same as column 1 no matter what is in column 1.   Like exposed cells that reference an original image/level the target can change and the reference will remain the same.  Change the reference within the expression and it will no longer be controlled by the same thing.

The proposed Expression Reference Manager proposes to sense when something referenced by an expression is being changed which in turn will bring the user into the loop with regard to preferences related to the change.  In particular to avoid circular references which we might unwittingly attempt to create.

**Comment by ladlon** [comment]
Yup, understood.

Okay, so it seems that the real 'catch' here, is that Tahoma2D/OT seems to have two 'column' items...  A sort of series of 'slots', and then these 'containers' that go into each slot (and can be moved from slot to slot).... and that the expressions reference the 'slots' rather than the (movable) container.  That's the rub... since it's the content (which would be the 'container') and not the 'slot' that you want to reference.

It seems odd that this is how it was coded originally, but I guess it is what it is... and hopefully the Expression Reference Manager succeeds in fixing the current issues.  It's good to see this is being discussed.

**Comment by ladlon** [comment]
One thing I found odd, although I THINK I know the reasoning behind it, after some thought, is that the expression editor (field where you type the epression) doesn't appear to be available unless you create at least 2 keyframes, and then select the curve in between.

Initially, I found that weird, since (at least in my use) I have the expression driving the column in a global sense... either it is directly referncing some other column's attribute, or by some mathematics (referencing the frame number, followed by perhaps some mathematical equation to modify the resulting raw value).... so the need for keyframes seems (initially) pointless, and in fact, couterintuitive/counterproductive... since I am usually using the expressions in order that I don't have to manually animate.

So, I had always been puzzled why you need to create two (ultimately unused/irrelevant) keyframes, rather than just entering an expression alone.  It kind of was annoying, having to do that.

But, then I realized that MAYBE the point of it was to give the ability to set a range for the expression, rather than assume it occurs for the entire length of the timeline... which, after realizing it, kind of made sense, and did seem then to make the need to create keyframes justified.  Is that the case here?

That said, setting keys IS still a bit tedious, in that I usually am not sure what the full duration of the finished piece is going to be, so I have to make an assumption, plus scoll/zoom over to the final frame to create the second key in its assumed spot (and then adjust that once I have my actual final duration... plus having to adjust it every time the timeline duration gets altered, so that the expression keys extend across the full timeline.

A small inconvenience, for sure, but still an inconvenience.  So, I was wondering...  Would it not be a good idea to also have a button on the expression editor (always available) which said 'Global Expression', and when clicked, it would assume a full-timeline duration for the expression (removing the need to manually set the two keys, and adjust them every time the timeline duration changes), and the expression editor would then be ungreyed and available.

Assuming, of course, I'm right in assuming that the keys are necessary as an indication of the duration/affect range of the expression.  If that's the case, then the slope itself is irrelevant, and if THAT is the case, then simply having a 'Global Expression' state that either dynamically always adjusts to be the same duration as the timeline... or simply have an 'infinite' duration, eliminating the need for it to be 'aware' of the duration... should be an easy solution... wouldn't it?

**Comment by RodneyBaker** [comment]
The term 'interpolation' is really short for 'keyframe interpolation' which suggests why we would need two keys to interpolate between... although technically speaking I don't think we absolutely need two keys in all cases because some processes may automatically infer there is a start and/or end and the our key (or breakdown).   This is why we can select a channel in the Function Editor and assign an interpolation to it without any keys set... Opentoonz will set keys for us on the first and last frames after we hit Apply.  The bottom line here is that we need to have two sets of data (keys) to interpolate through/against.

By default the value zero is entered for expressions (although it isn't set in a channel until applied by the user.
I find this to be very appropriate because the value zero locks the channel in its default position (i.e. with whatever default values are set  for say the x and y (or ew and ns) channels).   For scale a value of zero will make it disappear whereas a value of 100 will leave it at the default 100% scale.  

An interesting approach to keyframing then with a value such as zero set is to set two (or more) additional keys between the two extremes and then interpolate that (or those) segments with other values.  This is much like the workflow animators use when they use 'stepped' interpolations to block out rough animations.

Regarding your earlier thoughts on slots versus objects... you may be on track there although I tend to think of the containers a little differently.   To my way of thinking the 'slot' is the column... these are the same thing and inside that column container we have levels which are containers for images which can be exposed in the columns on every frame.  Each one of these containers... whether they be columns or levels... can have a title or name we use as a reference to that container.  The name is not the same as the container but is an attribute of it.  Similarly, we can adjust this title/name without disturbing the underlying or true object name which if changed would break all links to it.

We do have some options for setting 'global keys'.
In some programs this might serve to 'force keyframe' in all active channels.

In the world of interpolations there are a number of theories to include having no keys at all on the one hand... and having every frame maintain a key... and tons of thought and theory of what should happen in between.

To my way of thinking a Global expression would need more defining as to:  1) How global the expression actually is (for instance how many should it work on... using the term 'global' would seem to imply all channels  2) what cause and effect parameters in the expression itself can actually be globally interpreted by a given channel (this is made somewhat more difficult when we consider differing units and values... for example movement right/left (pixel units) versus rotations (degrees/angles).  A truly global expression would need to allow for these changes in orientation, intensity, etc.  in short, they'd need 'keys' or parameters of their own so that the rules governing them get followed.

A bit further and perhaps out of scope of this discussion would be expressions that actually target other objects and project values onto them.  Currently, expressions draw in data from other objects and mathematical expressions but there is no reason why we could not create a means to set an expression that pushed data onto specifically targeted objects which then would behave as if those were their own values.  Example:  An expression that points to columns 1, 2 and 3 and has each double in value (say of scale) for every frame.  This 'global expression' would not even need to be held inside a key on a timeline/channel but could be placed anywhere appropriate where the application would read it and project values onto columns 1, 2 and 3.
These empty 'keys' are in fact control points but with empty slots (as you've suggested) waiting for some value to be applied to them.  Offsets and layering of data then 'flavor' the actions accordingly.  From there it becomes mostly a matter of determining how data from different influences gets blended together.   In some programs this might be termed 'overloading'.  When multiple actions are applied to an object then a decision much be made to either replace the values, add the values on top of the other data or blend/average the values to some percentage.

![image](https://user-images.githubusercontent.com/2576432/96159741-a216e180-0eda-11eb-94b6-354d65156df6.png)

In the end, expressions are just sets of instructions or actions we want an object to take on as a property or attribute.
A property often being the underlying default values (at least to begin with) and and attribute being some value that is being gained.  We set 'keys' so that there is something there to contain and/or filter those values.

**Comment by RodneyBaker** [comment]
I ran into this and it seems appropriate to add to the conversation.
Specifically this is from a course where the instructor is suggesting that linear interpolations are a 'naive' approach.

> the general idea for a more accurate interpolation is:
> • Decompose the surrounding 4x4 matrix transformations around the current key frame into
> rotations, translations, and scales.
> • Linearly interpolate the translations and scales, and interpolate the rotations by converting to
> quaternions, slerping, and then converting the result back to a rotation matrix.
> • Recompose the constituents to give a transformation for the current frame.

One of the difficulties in a 'global expression' as hinted at before is with interpreting rotations in a linear fashion.
In 3D orientation we run into 'gimbal lock' where things get messy.
We might say, 'Well, we are only working in 2D' but that isn't quite the case.
In Opentoonz we have a number of methods for dealing with Z depth and stacking orders but they aren't currently presented via a 3D interface.

The primary reason I'm adding this is to suggest that solving for values on a 2D plane is not going to be sufficient to our greater purpose.  We must account for more in our interpolations.

**Comment by ladlon** [comment]
Wow, thanks for all that!  Some good reading for me to do.

To require two keys for regular interpolations (ease in, linear, etc) makes sense, and I have no arguement there.  It's literally the transition between two values/keys.

Where I was puzzled, in the current utilization of Tahoma2D, is that the Expression interpolation is greyed out, and requires two keys in order to even be accessible.  If, say, I am animating a column with the expression Frame * 10, it is (what I am perhaps incorrectly calling) a 'Global' expression (...in that it is active for the entire duration of the timeline).  It is an expression that is infinite in range, and self-contained.  So, it's puzzling why the current utilization of Tahoma2D requires two keys (which seem ultimately pointless, as their values, and perhaps even duration/postion are not used by the expression).  Why not just be able to type in an expression (such as the example I gave earlier) and that's it?  That's actually how it is done in something like AfterEffects.  I'm just not understanding why you have to create two keys in order to do an expression... at least that's what is happening over here.  Again, for OTHER interpolations (linear, ease, etc), it makes obvious sense.

Just wanted to quickly throw that in. I have to re-read and fully absorb all the content in your two posts!  (You snuck that last one in as I was writing this!)

**Comment by ladlon** [comment]
Ya, I think my terminology is very flawed, and maybe as a result, your thinking I'm talking about something more complex than I am trying to!  hehe...

I'm just puzzled why the use of expressions isn't done similar to that of AfterEffects... You can just apply an expression (ex. Frame*10) without any keys or anything like that, right away.  That doesn't seem to be the case in my version of Tahoma2D.

**Comment by ladlon** [comment]
I re-read your posts.  Ya, I am misusing the term 'Global'.  I am referring to the range of it within the timeline, not as a (true) global item, accessable to or affecting all others.  My bad.  I wasn't sure what to call what I was describing.

The only reason I even bring up a 'global' concept, is that I got the impression (from using Tahoma2D) that maybe the reason why the two keys were needed for an expression was to simply define a range within the timeline that the expression had control (...the values of the keys would still be irrelevant, but the position of the keys defined a range)...  Outside of that range, the expression isn't applied.

That was just my theory, as I couldn't otherwise understand why two keys were needed.

So, ya, I'm just confused about all that.

**Comment by ladlon** [comment]
I had a moment to set up a test, and it seems my theory was right (about the keys defining the active range.

(Sorry, bear with me... I'm still learning some of the differences between Tahoma2D and my previous software...)

Okay, so that's actually a nice feature (whereas in something like AfterAffects, the expression has an infinite range only).

So, that makes sense, and I like the added control, but for 90% of the expressions I do, they are intended to span the entire duration of the timeline (ex. Windmill rotating for the entire scene), so I'm wondering why we can't just apply an expression (without keys) and have Tahoma2D assume then it's for the full duration (.... what I mistakenly labeled as 'global').  Or, simply have a toggle button to indicate that it should be 'infinite' (so you not only don't have to create keys, but you also don't have to keep adjusting the frame location of the keys every time the timeline duration gets altered.  Keep everything as is, but add the ability to set an 'infinite duration' expression, which would then ungrey the expression editor, and allow you to just apply an expression right away.

**Comment by RodneyBaker** [comment]
There are several things going on here the first of which my wall of text might have obscured.
In order to have an interpolation we must have two keys.  If two keys are not presented, the program is simply hiding those keys from the user (this might be the case with After Effects but I don't recall off hand).
We simply cannot interpolate between nothing and nothing or between nothing. (no, that doesn't make sense).
We must define out things first and then interpolate between them.

If many cases what we see with more dynamic keyframe sets is that they are in fact issued as pairs or sets.
The first of which automatically scales between frame 0 (or alternatively frame 1) and the last frame of a sequence.
Subsequent keyframes then reference one of those initial keys (perhaps ideally via a percentage).
This makes it easier to dynamically scale when control points/keys are changed.

What it seems is that you are desiring an initial set of keys to be automatically set that are linked to the first and last frames of the current playrange.  Then when the playrange is modified those keys will change as well.

The primary thing that assigns the range of any set/pair of keys currently is the frame fields in the dialogue box.
And no, that is not very dynamic:

![image](https://user-images.githubusercontent.com/2576432/96168841-f88a1d00-0ee6-11eb-9602-da0dda1f4d24.png)

**Comment by ladlon** [comment]
Yes, again, let's use the simple expression in the rotation channel: Frame*10.

In something like AfterEffects, you simply type this expression, and it is active on all and any frames the timeline might have.  There is no in/out point (...although, admittingly, that feature is certainly a benefit).  I do not have to create any keys, just the expression.  Any frame I go to, it simply calculates the current frame, multiplies it by 10, and THAT becomes that frames rotation value.

Over here, what I am finding with Tahoma2D, is that it seems I have to set two keyframes just to have the expression field become available... even if the intention is to have it span infinitely.

I'm just wondering why it can't be set up (like AE) where I can choose to just set an infinite range expression (radio/toggle checkbox?), and then just type in my expression... rather than having to manually create keys, and then also having to then manually adjust their positions every time my timeline's duration grows or shrinks.  Since the expression is 'infinite range', no range is needed.

Am I supposed to be able to do that in the existing version?  It doesn't seem to be letting me.

**Comment by manongjohn** [comment]
Not that I want to derail this conversation as I'm sure something good will come out of it eventually, but this entire `bug` report is a wall of text.  Personally, this is a very hard read to begin with and the follow up conversation is quickly heading towards becoming War and Peace :)

I would ask to move this conversation elsewhere but as of right now I don't know where that should be. So after you guys have hashed out whatever it is you are working out, please `Hide` unnecessary comments, if possible, so it is a little more focused for a developer.

Feel free to disagree with me or think I'm being a **** but bug reports need to be a little more concise with supporting information so we can narrow down the issue and find a fix for it.

**Comment by ladlon** [comment]
Understood.  We can close this one up, if Rodney is cool with it.  Interesting conversation, to be sure.

The actual 'bug' is seemingly being addressed with the upcoming/proposed Expression Manager thing... so it's not like this issue hasn't already been noticed/acknowledged.

The only disadvantage to closing this thread, is that others will probably miss out on Rodney's interesting info.  I always worry that closing threads prevents other from seeing potentially valuable info/discussion, since many probably don't venture into the Closed section... but, I'm assuming that, of course.

Let me know.  I'm cool with whatever you choose.  I can close this if you want.

**Comment by manongjohn** [comment]
This site is primarily for developers to address bugs and work out new features, not necessarily a public forum for lengthy discussions for teaching purposes.  As interesting as the information might be, our goal is to close tickets and move on to the next one.

If you see a lengthy discussion it's probably because a Developer wants to work on something and needs more information/clarification to narrow requirements so they can determine scope and effort.

If the issue is resolved. close it.  If it's not resolved, keep it open.

**Comment by ladlon** [comment]
Where IS the more appropriate place for learning-based discussions?  This forum was the only one the site seems to point to.

**Comment by manongjohn** [comment]
I've just created a Google Group for Tahoma2D:  https://groups.google.com/g/tahoma2d.  Feel free to use it :)

**Comment by ladlon** [comment]
Cool.  Joined.
Okay, we haven't heard back from Rodney, but I imagine he wont' have any issue with us closing this thread down.

**Comment by RodneyBaker** [comment]
@ladlon A good place to discuss and explore such things live and in person is a discord (chat) channel.
There are several discords for Opentoonz and even one official one for Tahoma2D.

Opentoonz discord:  https://discord.gg/NQqjenD
