### ISSUE TITLE
Remove build skeleton mode of skeleton tool.

### ISSUE THREAD

**Issue by jeremybullock** [turtletooth/tahoma2d#497]
I'd like to remove the build skeleton mode of the skeleton tool, but wanted to throw this out there for discussion before any work is done.

The mode is not intuitive and there are two easier ways to create a skeleton - the schematic and the column headers in the xsheet.

**Comment by artisteacher** [comment]
I totally agree. It's too easy to parent the wrong thing with build skeleton mode.

**Comment by DarrenTAnims** [comment]
I really dislike the Build Skeleton mode and haven't tried to use it for a long time because it's so difficult to use.

**Comment by jrhyme** [comment]
@DarrenTAnims It is difficult for someone, but for someone it is necessary, like me, I am categorically against it!

**Comment by beeheemooth** [comment]
What?...
Wait, no, no, no.
 I don't know how you animate guys, but I use Build Skeleton all the time to snap columns and move the center (if you accidentally snap something to the wrong place, that's your problem, hehe) I totally oppose. Instead of the new "pinned center" for inverse kinematics, which everyone is waiting for, something else is being taken away from us. Maybe then give up skeletal animation altogether?

**Comment by artisteacher** [comment]
I hadn't realized you could move the center that way. However if you have any centers that are close together/overlapping, it is  really finicky parenting to the correct one. If you get it wrong, you have to use the schematic or xsheet column to fix it anyways.

**Comment by jeremybullock** [comment]
After playing around with this some more, I take it back.  It is certainly useful, but could maybe use some tips in the status bar or some other clarification.

**Comment by beeheemooth** [comment]
Even if several drawings in different columns have close centers, you can only move one drawing, the one around which the bounding box is displayed. You can switch between columns by simply clicking on the drawing. It goes without saying that the background and other columns that should not be involved in skeletal animation should be locked.
After you have selected a drawing, you can rotate it from any distance so as not to accidentally hook other drawings by clicking on the canvas. Moving the drawing requires more attention, since you need to hit the manipulator (I heard that Mac users have problems with this, as well as with the arrows for switching frames).
 Personally, I would remove the center offset point (in Animate mode) since this is not an animated parameter and it only gets in the way here. The center should just be configured in the Build Skeleton mode, and thus this mode justifies its right to exist.

**Comment by artisteacher** [comment]
> you need to hit the manipulator (I heard that Mac users have problems with this, as well as with the arrows for switching frames).

Only because the manipulator & arrows are crazy small. Look at the keyframe button for a comparison:
<img width="62" alt="Screen Shot 2020-11-16 at 6 19 25 PM" src="https://user-images.githubusercontent.com/21159116/99319851-4ec8e380-2838-11eb-8daa-def37b36ba05.png">



Ok, so looking at the manual, you can change the parent by dragging the square handle. That doesn't seem very intuitive to me. I don't get why the drag handle doesn't stay at the tip...

Some suggestions for status bar tips for Build skeleton:

- Click on drawings to switch
- Drag the root to set center
- Drag the square to link
